export const WORD_TRANSLATIONS: Record<string, string> = {
  aldar: "Алдар (аты)",
  kose: "Көсе (лақап аты)",
  is: "болып табылады",
  a: "бір",
  poor: "кедей",
  man: "адам",
  he: "ол",
  has: "бар",
  no: "жоқ",
  coat: "шапан / сырт киім",
  horse: "ат / жылқы",
  but: "бірақ",
  very: "өте",
  clever: "тапқыр / айлакер",
  one: "бір",
  day: "күн",
  sees: "көреді",
  rich: "бай",
  on: "үстінде",
  road: "жол",
  does: "жасайды",
  not: "жоқ",
  have: "ие болу",
  meets: "кездестіреді",
  dusty: "шаң басқан",
  famous: "әйгілі",
  his: "оның",
  cleverness: "тапқырлығы",
  owns: "иелік етеді",
  while: "кезінде",
  walking: "серуендеу",
  extremely: "шамадан тыс",
  proud: "тәкаппар",
  although: "қарамастан",
  clothes: "киімдер",
  renowned: "аты шыққан",
  across: "бойында",
  steppe: "ұлы дала",
  sharp: "өткір",
  wit: "ұшқыр ақыл",
  afternoon: "күндіз",
  wanders: "кезеді",
  lonely: "жалғыз",
  comes: "келеді",
  arrogant: "менмен",
  wealthy: "дәулетті",
  riding: "мініп келе жатқан",
  fine: "сәнді",
  despite: "қарамастан",
  possessing: "ие болу",
  earned: "жинады",
  reputation: "бедел",
  cunning: "қулық",
  silver: "күміс",
  tongue: "тіл",
  scorching: "ыстық",
  trudges: "аяғын басып келеді",
  deserted: "бос",
  fate: "тағдыр",
  delivers: "жеткізеді",
  encounter: "кездесу",
  insufferably: "шыдамыссыз",
  merchant: "көпес",
  wants: "қалайды",
  an: "бір (артикль)",
  idea: "ой / идея",
  looks: "қарайды",
  shouts: "айқайлайды",
  wolf: "қасқыр",
  scared: "қорыққан",
  jumps: "секіреді",
  down: "төмен",
  runs: "жүгіреді",
  away: "алысқа",
  fast: "жылдам",
  drops: "түсіріп жібереді",
  ground: "жер",
  takes: "алады",
  puts: "киеді",
  now: "қазір",
  rides: "мінеді",
  home: "үйге",
  tells: "айтып береді",
  friends: "достары",
  story: "әңгіме",
  laugh: "күледі",
  they: "олар",
  love: "жақсы көреді",
  tricks: "айлалар",
  or: "немесе",
  wearing: "киіп алған",
  beautiful: "әдемі",
  that: "сол",
  really: "шынымен",
  so: "сондықтан",
  thinks: "ойлайды",
  of: "-ның",
  plan: "жоспар",
  points: "нұсқайды",
  behind: "артында",
  hungry: "аш",
  coming: "келе жатқан",
  afraid: "қорыққан",
  off: "-дан түседі",
  back: "артқа",
  as: "ретінде",
  can: "мүмкіндігі бар",
  panic: "үрей",
  picks: "алады (жерден)",
  up: "жоғары",
  to: "-ға",
  laughing: "күліп",
  quietly: "тыныш",
  when: "қашан",
  villagers: "ауыл тұрғындары",
  hear: "естиді",
  too: "да",
  praise: "мақтайды",
  for: "үшін",
  trick: "айла",
  along: "бойымен",
  thick: "қалың",
  decides: "шешім қабылдайды",
  himself: "өзі",
  with: "-мен",
  over: "арқылы",
  shoulder: "иық",
  frightened: "қорыққан",
  expression: "кейіп",
  pack: "тобыр",
  wolves: "қасқырлар",
  running: "жүгіріп келе жатқан",
  toward: "қарай",
  them: "оларды",
  immediately: "дереу",
  from: "-дан",
  heavy: "ауыр",
  faster: "жылдамырақ",
  disappears: "жоғалады",
  looking: "қарап",
  calmly: "сабырмен",
  climbs: "мінеді",
  onto: "үстіне",
  feeling: "сезініп",
  pleased: "риза",
  evening: "кеш",
  neighbors: "көршілер",
  everyone: "барлығы",
  outsmarted: "тапқырлықпен жеңілді",
  by: "арқылы",
  nothing: "ештеңе",
  wrapped: "оранған",
  magnificent: "керемет",
  deserves: "лайық",
  far: "алыс",
  more: "көбірек",
  than: "-ға қарағанда",
  owner: "иесі",
  within: "ішінде",
  moments: "сәттер",
  invented: "ойлап тапты",
  feigning: "жалған көрсетіп",
  terror: "үрей",
  glances: "көз тастайды",
  cries: "айқайлайды",
  racing: "жарысып келе жатқан",
  convinced: "сенімді",
  performance: "ойын",
  leaps: "секіреді",
  tears: "жыртады",
  unhindered: "кедергісіз",
  sprints: "жүгіреді",
  without: "-сыз",
  backward: "артқа қарай",
  glance: "көз қарас",
  leaving: "қалдырып",
  both: "екеуі де",
  gathers: "жинайды",
  abandoned: "тасталған",
  mounts: "мінеді",
  leisurely: "асықпай",
  thoroughly: "түбегейлі",
  amused: "көңілденген",
  easily: "оңай",
  wealth: "байлық",
  separated: "бөлінген",
  foolishness: "ақымақтық",
  later: "кейінірек",
  recounts: "қайта айтып береді",
  tale: "ертегі",
  whole: "бүкіл",
  roars: "гүрілдейді",
  expense: "есебінен",
  neither: "не бірі, не екіншісі",
  resplendent: "жарқыраған",
  mounted: "мінген",
  upon: "үстінде",
  ever: "әрдайым",
  alert: "сергек",
  opportunity: "мүмкіндік",
  resolves: "шешім қабылдайды",
  vain: "мақтаншақ",
  conceived: "ойлап тапты",
  ingenious: "тапқыр",
  scheme: "айла-шарғы",
  adopting: "қабылдап",
  pure: "таза",
  ravenous: "өте аш",
  bearing: "беттеп келе жатқан",
  open: "ашық",
  overcome: "жеңілген",
  flings: "лақтырады",
  lighten: "жеңілдету",
  flight: "қашу",
  flees: "қашады",
  suppressing: "тежеп",
  retrieves: "қайтарып алады",
  unhurried: "асықпай",
  marveling: "таңданып",
  pride: "мақтаныш",
  good: "жақсы",
  sense: "ақыл-парасат",
  fire: "от",
  entire: "бүкіл",
  erupts: "жарылады",
  legend: "аңыз",
  trickster: "тапқыр алаяқ",
  grows: "өседі",
  little: "аздап",
  larger: "үлкенірек",
  still: "әлі де",
  and: "және",
  at: "-да",
  be: "болу",
  big: "үлкен",
  him: "оны",
  how: "қалай",
  in: "-де",
  it: "ол (зат есім)",
  its: "оның",
  koses: "Көсенің",
  laughs: "күледі",
  laughter: "күлкі",
  look: "қара!",
  mans: "адамның",
  merchants: "көпестің",
  most: "ең",
  much: "көп",
  nor: "де емес",
  once: "бір рет",
  out: "сыртқа",
  pace: "қарқын",
  panics: "үрейленеді",
  parted: "айырылды",
  run: "жүгіру",
  steppes: "дала",
  such: "мұндай",
  the: "анықтауыш артикль",
  village: "ауыл",
  warm: "жылы",
  was: "болды",
  wasted: "далада қалды (бекерге кетті)",
  above: "жоғарыда",
  advances: "алға жылжиды",
  advisor: "кеңесші",
  advisors: "кеңесшілер",
  after: "кейін",
  afterward: "содан кейін",
  all: "барлық",
  amazed: "таңғалған",
  another: "тағы бір",
  answer: "жауап",
  answering: "жауап беру",
  answers: "жауап береді",
  any: "кез келген",
  anywhere: "кез келген жерге",
  arduous: "ауыр, машақатты",
  are: "болып табылады",
  arrives: "келеді",
  asking: "сұрау",
  asks: "сұрайды",
  assembled: "жиналған",
  astonished: "таңғалған",
  astounded: "қатты таңғалған",
  bad: "жаман",
  bear: "көтеру, шыдау",
  because: "себебі",
  becomes: "болады, айналады",
  before: "алдында",
  begins: "бастайды",
  birth: "туу",
  born: "туған",
  breadth: "ені, кеңдігі",
  briefly: "қысқаша",
  burden: "ауыртпалық",
  capable: "қабілетті",
  carefully: "мұқият",
  careless: "немқұрайлы",
  carry: "алып жүру",
  circumstances: "жағдайлар",
  claims: "мәлімдейді",
  considers: "ойланады",
  constitutes: "құрайды",
  continues: "жалғасады",
  counsel: "кеңес",
  counselor: "кеңесші",
  court: "сарай",
  cruel: "қатал",
  declares: "жариялайды",
  deeply: "терең",
  depth: "тереңдік",
  desire: "тілек, ынта",
  difficult: "қиын",
  distinction: "ерекшелік",
  driven: "итермеленген",
  each: "әрбір",
  eager: "ынталы",
  eclipses: "басып озады",
  elegance: "әдемілік, нәзіктік",
  else: "басқа",
  eventually: "ақыр соңында",
  every: "әрбір",
  exhausting: "шаршататын",
  existence: "өмір сүру",
  experience: "тәжірибе",
  explaining: "түсіндіру",
  extends: "таралады",
  extent: "дәреже, көлем",
  extraordinary: "ерекше",
  fastest: "ең жылдам",
  final: "соңғы",
  finally: "ақырында",
  first: "бірінші",
  fleeting: "өткінші",
  follows: "соңынан ереді",
  force: "күш",
  formidable: "күрделі, қиын",
  forward: "алға",
  front: "алдыңғы жақ",
  full: "толық",
  gauge: "өлшеу",
  generation: "ұрпақ",
  genuine: "шынайы",
  go: "бару",
  greater: "үлкенірек",
  grow: "өседі",
  happy: "қуанышты",
  hard: "қиын, қатты",
  hardest: "ең қиын",
  heart: "жүрек",
  hearts: "жүректер",
  heaviest: "ең ауыр",
  hesitation: "екіұдайлық",
  honored: "құрметті",
  human: "адами",
  humankind: "адамзат",
  humble: "қарапайым",
  hurtful: "ауыртатын",
  imaginable: "елестетуге болатын",
  impossible: "мүмкін емес",
  impressed: "әсерленген",
  indispensable: "таптырмайтын, қажетті",
  inquires: "сұрайды",
  inquiry: "сұрау",
  insight: "түсінік, парасат",
  intellect: "парасат",
  intelligence: "зеректік",
  into: "ішіне",
  itself: "өзі",
  judgment: "пайымдау",
  just: "тек қана",
  khan: "хан",
  kingdom: "хандық, патшалық",
  know: "білу",
  known: "белгілі",
  labor: "еңбек",
  last: "соңғы",
  lingers: "ұзақ сақталады",
  long: "ұзақ",
  many: "көп",
  measure: "өлшеу",
  moment: "сәт",
  my: "менің",
  observing: "байқай отырып",
  only: "тек",
  onward: "әрі қарай",
  other: "басқа",
  others: "басқалар",
  "others'": "басқалардың",
  pain: "ауырсыну",
  passing: "өтіп жатқан",
  pause: "үзіліс",
  pauses: "үзіліс жасайды",
  people: "адамдар",
  person: "адам",
  place: "орын",
  pleasure: "ләззат",
  poses: "қояды",
  position: "орын, лауазым",
  possesses: "иеленеді",
  poverty: "кедейшілік",
  powerful: "қуатты",
  proceeds: "жалғастырады",
  proclaims: "жариялайды",
  profound: "терең",
  profundity: "тереңдік",
  question: "сұрақ",
  questions: "сұрақтар",
  quite: "өте",
  realm: "патшалық, аймақ",
  reflection: "ойлану",
  reflects: "ойланады",
  regarded: "саналады",
  remarkable: "тамаша, ерекше",
  renown: "даңқ",
  replies: "жауап береді",
  replying: "жауап бере отырып",
  respected: "құрметті",
  response: "жауап",
  responds: "жауап береді",
  rising: "көтерілу",
  rivals: "теңдесе алады",
  satisfaction: "қанағаттану",
  satisfied: "қанағаттанған",
  says: "айтады",
  second: "секунд, екінші",
  securing: "бекіту",
  seemingly: "сыртқы көрінісінше",
  serve: "қызмет ету",
  serves: "қызмет етеді",
  settles: "орналасады, тұрақтайды",
  sheer: "таза, мүлдем",
  since: "себебі",
  single: "жалғыз",
  sleep: "ұйқы",
  slightest: "ең кішкентай",
  smiles: "жымиады",
  sought: "ізделді",
  span: "аралық, уақыт кезеңі",
  spoken: "айтылған",
  struck: "әсерленген",
  subject: "тақырып",
  summons: "шақырады",
  surpasses: "асып түседі",
  surprised: "таңғалған",
  sweetest: "ең тәтті",
  sweetness: "тәттілік",
  test: "сынау",
  their: "олардың",
  then: "сонда",
  there: "сол жерде",
  thing: "зат, нәрсе",
  this: "бұл",
  though: "дегенмен",
  thought: "ой",
  thoughtful: "ойлы",
  thoughtfully: "ойлана отырып",
  thoughtless: "ойланбай",
  three: "үш",
  through: "арқылы",
  throughout: "бойы",
  toil: "ауыр еңбек",
  travel: "саяхаттау, жету",
  traversing: "кесіп өту",
  true: "шынайы",
  truly: "шынымен",
  trusted: "сенімді",
  ultimately: "ақыр соңында",
  unanswerable: "жауап беруге келмейтін",
  undiminished: "кемімеген",
  uttered: "айтылған",
  valued: "бағаланатын",
  visibly: "көрінеу",
  walk: "жүру",
  weight: "салмақ",
  what: "не",
  who: "кім",
  widely: "кеңінен",
  widespread: "кең таралған",
  wisdom: "даналық",
  wise: "дана",
  wisest: "ең дана",
  word: "сөз",
  work: "жұмыс",
  works: "жұмыс істейді",
  world: "әлем",
  year: "жыл",
  years: "жылдар",
  you: "сен, сіз",
  zhirenshe: "Жиренше (аты)"
};

export const DICT = {
  kk: {
    skip: "ÖTKİZİP JÏBERŪ",
    enter: "BASTAU",
    greeting: "ARMISIN, OQUŞY",
    homeSubtitle: "Qazaq fol'klory men dala añyzdary negızınde jasatylğan innovaciälyq EdTech platformasy.",
    collectionTitle: "AÑYZDAR JINAĞY",
    startReading: "OQUDY BASTAU",
    quizTitle: "Tekseru sūragy",
    checkAnswer: "JAUAPTY TEKSERU",
    tryAgain: "Qaita baiqap köru",
    speakTitle: "Aıtylym jattyğuy",
    speakSubtitle: "Tömendegi söılemdı daustap oqyñyz:",
    recording: "DAUS JAZYLÝDA...",
    pressMic: "MIKROFONDI BASYP SÖILEÑIZ",
    accuracy: "DƏL'DİK",
    greatIntonation: "Öte jaqsy intonaciä! +15 XP qosyldy.",
    navHome: "BASTY",
    navRead: "OQÝ",
    navQuiz: "SYNAQ",
    navSpeak: "DYBYS",
    navProfile: "PROFIL",
    takeQuiz: "SYNAQTAN ÖTU",
    correctMsg: "DŪRYS! +25 XP JINALDY 🔥",
    wrongMsg: "QATE! PARAGRAPHTY QAITA OQYP ŞYĞYÑYZ",
    storyDesc: "Aldar Köse men baıdyñ şapany turaly ailakerlik pen tapqyrlyq añyzy.",
    sceneAnimation: "CINEMATIC VISUAL SCENE",
    selectLevelTitle: "DEÑGEIDİ TAÑDAÑYZ",
    selectLevelSub: "Ağılşyn tilı deñgeııñızge saqtaıynsha mətındı tañdañyz:",
    selectStoryTitle: "AÑYZDY TAÑDAÑYZ",
    selectStorySub: "Oqu üşin bir añyzdy tañdañyz:",
    changeLevel: "DEÑGEI",
    profileTitle: "OQUŞY PROFILİ",
    totalXpLabel: "JINALĞAN XP",
    streakLabel: "ÜZILMEITIN KÜNDER",
    startDateLabel: "BASTALĞAN KÜN",
    levelStatus: "MƏRTEBE: ERTEGI ENGLISH AMBASSADOR",
    shareBuklet: "MURA BUKLETİN AŞU",
    bukletHeader: "QAZAQSTAN MURA PASSPORTY",
    closeBuklet: "JABU",
    downloadBuklet: "BÝKLETKİ JÝKTEÝ",
    tapWordHint: "Sözge basyp audarmasyn qarañyz zhəne dauspen oqyñyz.",
    interactiveChoiceTitle: "INTERAKTIVTI TAÑDAU (VISUAL NOVEL)",
    choicePrompt: "Aldar Köse osy zhғdaıda ne isteui kerek?",
    artifactUnlocked: "JANA MURA ARTEFAKTY AŞYLMDY! 🏛️"
  },
  en: {
    skip: "SKIP INTRO",
    enter: "EXPLORE TALES",
    greeting: "WELCOME LEARNER",
    homeSubtitle: "An innovative EdTech platform bridging Kazakh steppe folklore and global English learning.",
    collectionTitle: "HERITAGE TALES",
    startReading: "START READING",
    quizTitle: "Comprehension Check",
    checkAnswer: "CONFIRM ANSWER",
    tryAgain: "Try again",
    speakTitle: "Pronunciation Coach",
    speakSubtitle: "Read the following sentence aloud:",
    recording: "RECORDING IN PROGRESS...",
    pressMic: "TAP MICROPHONE TO SPEAK",
    accuracy: "ACCURACY",
    greatIntonation: "Flawless intonation! +15 XP added.",
    navHome: "HOME",
    navRead: "READ",
    navQuiz: "QUIZ",
    navSpeak: "SPEAK",
    navProfile: "PROFILE",
    takeQuiz: "TAKE QUIZ",
    correctMsg: "EXCELLENT! +25 XP GAINED 🔥",
    wrongMsg: "INCORRECT! RE-READ THE PARAGRAPH",
    storyDesc: "A tale of wit and cleverness featuring Aldar Kose and the rich man's coat.",
    sceneAnimation: "CINEMATIC SCENE",
    selectLevelTitle: "SELECT DIFFICULTY",
    selectLevelSub: "Choose your target English level to unlock the tailored text:",
    selectStoryTitle: "SELECT A STORY",
    selectStorySub: "Choose a legend to read:",
    changeLevel: "LEVEL",
    profileTitle: "LEARNER PASSPORT",
    totalXpLabel: "TOTAL XP EARNED",
    streakLabel: "ACTIVE STREAK",
    startDateLabel: "MEMBER SINCE",
    levelStatus: "RANK: ERTEGI ENGLISH AMBASSADOR",
    shareBuklet: "GENERATE HERITAGE BOOKLET",
    bukletHeader: "KAZAKHSTAN HERITAGE PASSPORT",
    closeBuklet: "CLOSE",
    downloadBuklet: "DOWNLOAD BOOKLET",
    tapWordHint: "Tap any word to see its translation and hear the voice audio.",
    interactiveChoiceTitle: "INTERACTIVE STORY BRANCH",
    choicePrompt: "What should Aldar Kose do in this situation?",
    artifactUnlocked: "NEW CULTURAL ARTEFACT UNLOCKED! 🏛️"
  }
};

export const BG_VIDEO_ASSETS = {
  intro: "/home.mp4",
  home: "/home.mp4",
  read: "/story.mp4",
  quiz: "/quiz.mp4",
  speak: "/speak.mp4",
  profile: "/home.mp4",
};

export const LEVEL_DETAILS = [
  { id: "A1", title: "BEGINNER", desc: "Karapayım so'zder men qysqa so'ylemler", badge: "A1" },
  { id: "A2", title: "ELEMENTARY", desc: "Negızgı leksika men qatynas frazalary", badge: "A2" },
  { id: "B1", title: "INTERMEDIATE", desc: "Añyz ben süjet terıñdıgı, bai grammatika", badge: "B1" },
  { id: "B2", title: "UPPER-INT", desc: "Kürdelı leksika men bayau stil'lık oylar", badge: "B2" },
  { id: "C1", title: "ADVANCED", desc: "Tolıq etno-poetika men akademialyq til", badge: "C1" },
];

export const STORIES = [
  {
    id: "aldar_kose",
    title: "ALDAR KÖSE & THE RICH MAN'S COAT",
    sceneLabel: "CHAPTER I · STEPPE LEGENDS",
    storyDesc: { en: "A tale of wit and cleverness featuring Aldar Kose and the rich man's coat.", kk: "Aldar Köse men baıdyñ şapany turaly ailakerlik pen tapqyrlyq añyzy." },
    choicePrompt: "What should Aldar Kose do in this situation?",
    choiceOptionA: "✨ A) Use a clever joke to trick the wealthy merchant",
    choiceOptionB: "🐴 B) Walk past him proudly without saying a word",
    levels: {
      A1: "Aldar Kose is a poor man. He has no coat. He has no horse. But he is very clever. One day he sees a rich man on the road. The rich man has a big warm coat. Aldar Kose wants the coat. He has an idea. He looks behind the rich man. He shouts, \"Look! A wolf!\" The rich man is scared. He jumps down. He runs away fast. He drops his warm coat on the ground. Aldar Kose takes the coat. He puts it on. Now he is warm. He rides the horse home. He tells his friends the story. They laugh and laugh. They love his clever tricks.",
      A2: "Aldar Kose is a poor but very clever man. He does not have a coat or a horse. One day, he meets a rich man on the dusty road. The rich man is riding a fine horse and wearing a beautiful warm coat. Aldar Kose really wants that coat, so he thinks of a clever plan. He points behind the rich man and shouts, \"Look! A hungry wolf is coming!\" The rich man is very afraid. He jumps off his horse and runs away as fast as he can. In his panic, he drops his warm coat on the ground. Aldar Kose picks up the coat and puts it on. He rides the horse back to his village, laughing quietly. When the villagers hear the story, they laugh too and praise Aldar Kose for his clever trick.",
      B1: "Aldar Kose is a poor man, but he is famous for his cleverness. He owns no coat and no horse. One day, while walking along a dusty road, he meets an extremely rich and proud man riding a fine horse and wearing a thick, warm coat. Aldar Kose decides that he wants that coat for himself, so he comes up with a clever plan. He looks over the rich man's shoulder with a frightened expression and shouts that a pack of hungry wolves is running toward them. The rich man panics immediately. He jumps down from his horse, drops his heavy coat so that he can run faster, and disappears down the road without looking back. Aldar Kose calmly picks up the warm coat, puts it on, and climbs onto the horse. He rides back to his village feeling very pleased with himself. That evening, he tells the story to his neighbors, and everyone laughs at how the proud rich man was outsmarted by a poor but clever man.",
      B2: "Although Aldar Kose owns nothing but the clothes on his back, he is renowned across the steppe for his sharp wit. One dusty afternoon, as he wanders along a lonely road, he comes across an arrogant, wealthy man riding a fine horse and wrapped in a magnificent, thick coat. Aldar Kose immediately decides that he deserves that coat far more than its owner does, and within moments he has invented a plan. Feigning terror, he glances over the rich man's shoulder and cries out that a pack of wolves is racing toward them across the steppe. Convinced by Aldar Kose's performance, the wealthy man panics, leaps from his horse, and tears off his coat so that he can run unhindered. He sprints away without a backward glance, leaving both horse and coat behind. Aldar Kose calmly gathers the abandoned coat, puts it on, mounts the horse, and rides home at a leisurely pace, thoroughly amused by how easily wealth can be separated from foolishness. When he later recounts the tale to his neighbors, the whole village roars with laughter at the rich man's expense.",
      C1: "Despite possessing neither coat nor horse, Aldar Kose has earned a reputation across the steppe for his cunning wit and silver tongue. One scorching afternoon, as he trudges along a dusty, deserted road, fate delivers him an encounter with an insufferably wealthy merchant, resplendent in a magnificent coat and mounted upon a fine horse. Aldar Kose, ever alert to opportunity, resolves at once that such a coat is wasted on so vain a man, and within moments he has conceived an ingenious scheme. Adopting an expression of pure terror, he glances over the merchant's shoulder and cries that a ravenous pack of wolves is bearing down upon them across the open steppe. Thoroughly convinced, the merchant is overcome with panic; he flings himself from his horse, tears off his heavy coat to lighten his flight, and flees down the road without so much as a backward glance. Aldar Kose, suppressing his laughter, calmly retrieves the abandoned coat, mounts the merchant's horse, and rides home at an unhurried pace, marveling at how easily pride and wealth can be parted from good sense. That evening, as he recounts the tale by the fire, the entire village erupts in laughter, and Aldar Kose's legend as the steppe's most cunning trickster grows a little larger still.",
    },
    quizQuestions: [
      {
        type: "mcq",
        q: "Why was Aldar Kose famous across the steppe?",
        options: ["His rich golden coat", "His sharp wit and cleverness", "His large army of horses", "His castle in the mountains"],
        correct: 1
      },
      {
        type: "mcq",
        q: "What did Aldar Kose NOT own?",
        options: ["A coat and a horse", "A house and land", "Books and gold", "Sheep and camels"],
        correct: 0
      },
      {
        type: "fillblank",
        sentence: "Aldar Kose shouted, \"Look! A ___ is coming!\"",
        options: ["merchant", "wolf", "horse", "villager"],
        correct: 1
      },
      {
        type: "mcq",
        q: "What trick did Aldar Kose use to get the coat?",
        options: ["He offered to buy it", "He challenged the man to a race", "He shouted that wolves were coming", "He asked the man's wife for it"],
        correct: 2
      },
      {
        type: "fillblank",
        sentence: "The rich man jumped off his horse and ___ away as fast as he could.",
        options: ["walked", "ran", "rode", "crawled"],
        correct: 1
      },
      {
        type: "mcq",
        q: "What did the rich man do when he panicked?",
        options: ["He hid behind a rock", "He dropped his coat and ran away", "He fought off the wolves", "He called for help"],
        correct: 1
      },
      {
        type: "mcq",
        q: "How did the story end?",
        options: ["The rich man caught Aldar Kose", "Aldar Kose lost the horse too", "Aldar Kose rode home and the village laughed at the story", "The wolves really did appear"],
        correct: 2
      },
    ],
  },
  {
    id: "zhirenshe",
    title: "ZHIRENSHE & THE KHAN'S THREE QUESTIONS",
    sceneLabel: "CHAPTER II · STEPPE LEGENDS",
    storyDesc: { en: "A tale of wisdom featuring Zhirenshe, the khan's wisest advisor.", kk: "Jirenşe şeşen men handyñ üş suragy turaly danalyq añyzy." },
    choicePrompt: "What should Zhirenshe do in this situation?",
    choiceOptionA: "🧠 A) Answer boldly, trusting his own wisdom",
    choiceOptionB: "🤫 B) Stay silent and let the khan decide alone",
    levels: {
      A1: "Zhirenshe is a poor man, but he is very wise. He works for a khan. One day, the khan wants to test him. The khan asks three hard questions. \"What is the fastest thing in the world?\" Zhirenshe answers, \"Thought is the fastest thing. It can go anywhere in one second.\" The khan is surprised. He asks another question. \"What is the sweetest thing in the world?\" Zhirenshe says, \"Sleep after hard work is the sweetest thing.\" The khan smiles. He asks the last question. \"What is the heaviest thing in the world?\" Zhirenshe thinks for a moment. He says, \"A bad word is the heaviest thing. People carry it in their hearts for many years.\" The khan is very happy. He says, \"You are truly wise, Zhirenshe.\" From that day, Zhirenshe becomes the khan's most trusted advisor.",
      A2: "Zhirenshe is a poor but extremely wise man who works as an advisor for a powerful khan. One day, the khan decides to test his wisdom with three difficult questions. First, he asks, \"What is the fastest thing in the world?\" Zhirenshe thinks for a moment and answers, \"Thought is the fastest thing, because it can travel anywhere in just one second.\" The khan is quite surprised by this clever answer. Then he asks a second question: \"What is the sweetest thing in the world?\" Zhirenshe replies, \"Sleep after a long day of hard work is the sweetest thing of all.\" The khan smiles with satisfaction. Finally, he asks the hardest question: \"What is the heaviest thing in the world?\" Zhirenshe considers carefully before answering, \"A cruel word is the heaviest thing, because people carry it in their hearts for many long years.\" The khan is deeply impressed and declares, \"You are truly the wisest man in my kingdom, Zhirenshe.\" From that day forward, Zhirenshe becomes the khan's most trusted and respected advisor.",
      B1: "Zhirenshe is a poor man by birth, but he is famous throughout the steppe for his remarkable wisdom, and he serves as a trusted advisor to a powerful khan. One day, the khan decides to test the true depth of Zhirenshe's intelligence by asking him three seemingly impossible questions in front of the entire court. The first question is, \"What is the fastest thing in the world?\" Without hesitation, Zhirenshe replies that thought is the fastest thing of all, since it can travel to any place in the world in a single second. The khan, visibly impressed, poses his second question: \"What is the sweetest thing in the world?\" Zhirenshe considers the question and answers that sleep after a long day of exhausting labor is the sweetest experience a person can know. Pleased with this answer, the khan asks his final and most difficult question: \"What is the heaviest thing in the world?\" Zhirenshe pauses thoughtfully before replying that a cruel or hurtful word is the heaviest burden of all, because people carry the pain of it in their hearts for many years afterward. Thoroughly amazed by such profound wisdom, the khan declares that Zhirenshe is the wisest man in the entire kingdom, and from that day onward, Zhirenshe becomes his most trusted and honored advisor.",
      B2: "Although born into poverty, Zhirenshe has earned widespread renown across the steppe for his extraordinary wisdom, eventually rising to serve as one of the khan's most valued advisors. One day, eager to measure the true extent of his advisor's intellect, the khan summons the entire court and poses three seemingly unanswerable questions. \"What is the fastest thing in the world?\" he begins. Without a moment's hesitation, Zhirenshe responds that thought itself is the fastest thing imaginable, capable of traversing the entire world in the span of a single second. Visibly impressed, the khan proceeds to his second question: \"What, then, is the sweetest thing in the world?\" Zhirenshe reflects briefly before explaining that sleep, when it follows a long day of exhausting labor, surpasses every other pleasure in sweetness. Satisfied, the khan poses his final and most formidable question: \"What is the heaviest thing in all the world?\" After a thoughtful pause, Zhirenshe answers that a cruel or thoughtless word is the heaviest burden a person can bear, for its weight lingers in the heart for years, long after it was spoken. Astonished by the depth of such wisdom, the khan proclaims before the entire court that no one in his kingdom possesses greater insight than Zhirenshe. From that day forward, Zhirenshe's counsel is sought above all others, and his reputation as the wisest man on the steppe continues to grow with each passing year.",
      C1: "Though he was born into humble circumstances, Zhirenshe has, through sheer force of intellect, earned a reputation for wisdom that extends across the entire steppe, ultimately securing his position as the khan's most indispensable advisor. One day, driven by a desire to gauge the true measure of his counselor's insight, the khan summons the full court and poses three questions widely regarded as unanswerable. \"What,\" he inquires, \"is the fastest thing in existence?\" Without the slightest hesitation, Zhirenshe replies that thought itself claims that distinction, capable as it is of traversing the breadth of the world in the span of a single fleeting second. Visibly struck by the elegance of this response, the khan advances to his second inquiry: \"And what, then, is the sweetest thing in the world?\" Zhirenshe pauses only briefly before observing that sleep, when it arrives after a day of arduous toil, eclipses every other pleasure known to humankind. Thoroughly satisfied, the khan poses his final and most formidable question: \"What, above all else, is the heaviest thing in existence?\" After a moment of genuine reflection, Zhirenshe answers that a cruel or careless word constitutes the heaviest burden imaginable, for its weight settles into the human heart and lingers there, undiminished, for years after it was first uttered. Astounded by the profundity of such wisdom, the khan declares before the assembled court that no subject in his realm rivals Zhirenshe in insight or judgment. From that day forward, Zhirenshe's counsel is sought above all others', and his legend as the wisest man ever to walk the steppe continues to grow with every passing generation.",
    },
    quizQuestions: [
      {
        type: "mcq",
        q: "What made Zhirenshe famous throughout the kingdom?",
        options: ["His great wealth", "His remarkable wisdom", "His powerful army", "His fast horse"],
        correct: 1
      },
      {
        type: "mcq",
        q: "What was Zhirenshe's role for the khan?",
        options: ["A soldier", "A trusted advisor", "A merchant", "A farmer"],
        correct: 1
      },
      {
        type: "fillblank",
        sentence: "The khan decided to test Zhirenshe with three ___ questions.",
        options: ["easy", "difficult", "short", "silly"],
        correct: 1
      },
      {
        type: "mcq",
        q: "According to Zhirenshe, what is the fastest thing in the world?",
        options: ["A horse", "Thought", "Light", "The wind"],
        correct: 1
      },
      {
        type: "mcq",
        q: "What did Zhirenshe say is the sweetest thing in the world?",
        options: ["Honey", "Money", "Sleep after hard work", "A kind word"],
        correct: 2
      },
      {
        type: "fillblank",
        sentence: "Zhirenshe said a ___ word is the heaviest thing in the world.",
        options: ["bad", "long", "loud", "foreign"],
        correct: 0
      },
      {
        type: "mcq",
        q: "How did the khan react at the end of the story?",
        options: ["He punished Zhirenshe", "He made Zhirenshe his most trusted advisor", "He sent Zhirenshe away", "He ignored the answers"],
        correct: 1
      },
    ],
  },
];

export const ACHIEVEMENTS = [
  {
    id: "quiz_first",
    icon: "🎯",
    title: "First Steps",
    desc: "Complete your first quiz",
    check: (s: any) => s.quizzesCompleted >= 1,
  },
  {
    id: "words_25",
    icon: "📚",
    title: "Word Collector",
    desc: "Save 25 words to your vocabulary bank",
    check: (s: any) => s.savedWordsCount >= 25,
  },
  {
    id: "quiz_perfect",
    icon: "🏆",
    title: "Flawless",
    desc: "Score 100% on a quiz",
    check: (s: any) => s.perfectQuizzes >= 1,
  },
  {
    id: "words_100",
    icon: "🏺",
    title: "Vocabulary Keeper",
    desc: "Save 100 words to your vocabulary bank",
    check: (s: any) => s.savedWordsCount >= 100,
  },
  {
    id: "level_5",
    icon: "⭐",
    title: "Rising Nomad",
    desc: "Reach Level 5 (500 XP)",
    check: (s: any) => s.xp >= 500,
  },
];
